/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'api-usage',
    path: '/api-usage',
    component: 'layout.base$view.api-usage',
    meta: {
      title: 'api-usage',
      i18nKey: 'route.api-usage',
      icon: 'mdi:chart-line',
      roles: ['ADMIN']
    }
  },
  {
    name: 'chat-history',
    path: '/chat-history',
    component: 'layout.base$view.chat-history',
    meta: {
      title: 'chat-history',
      i18nKey: 'route.chat-history',
      roles: ['USER', 'LIBRARY_ADMIN']
    }
  },
  {
    name: 'chats',
    path: '/chats',
    component: 'layout.base$view.chats',
    meta: {
      title: 'chats',
      i18nKey: 'route.chats',
      icon: 'mdi:chat',
      roles: ['USER', 'LIBRARY_ADMIN']
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'knowledge-base',
    path: '/knowledge-base',
    component: 'layout.base$view.knowledge-base',
    meta: {
      title: 'knowledge-base',
      i18nKey: 'route.knowledge-base',
      icon: 'mdi:bookshelf',
      roles: ['LIBRARY_ADMIN', 'ADMIN']
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'org-tag',
    path: '/org-tag',
    component: 'layout.base$view.org-tag',
    meta: {
      title: 'org-tag',
      i18nKey: 'route.org-tag',
      icon: 'mdi:tag-outline',
      roles: ['ADMIN']
    }
  },
  {
    name: 'user-monitor',
    path: '/user-monitor',
    component: 'layout.base$view.user-monitor',
    meta: {
      title: 'user-monitor',
      i18nKey: 'route.user-monitor',
      icon: 'mdi:account-supervisor',
      roles: ['ADMIN']
    }
  }
];
